export const universities =  [
"University of Aberdeen",
"Abertay University",
"Aberystwyth University",
"Anglia Ruskin University, Cambridge",
"Arden University",
"Aston University",
"Bangor University",
"University of Bath",
"Bath Spa University",
"University of Bedfordshire",
"University of Birmingham",
"Birmingham City University",
"University College Birmingham",
"Bishop Grosseteste University",
"University of Bolton",
"The Arts University Bournemouth",
"Bournemouth University",
"BPP University",
"University of Bradford",
"University of Brighton",
"University of Bristol",
"Brunel University",
"University of Buckingham", 
"Buckinghamshire New University",
"King's College",
"University of Cambridge",
"Canterbury Christ Church University",
"Cardiff Metropolitan University",
"Cardiff University",
"University of Chester",
"University of Chichester",
"Coventry University",
"Cranfield University",
]